# Properties of Dot Product - Lab

## Introduction

In this lab we shall look at some interesting properties of a Dot product type matrix multiplication. Understanding these properties will become useful as we move forward with machine learning advanced linear algebra. The lab will require you to calculate results to provide a proof for these properties.

## Objectives
You will be able to:
* Understand and analytically explain Distributive, Commutative and Associative properties of dot product

## Instructions

* For each property, create suitably sized matrices with random data and prove the equations 
* Ensure that size/dimension assumptions are met while performing calculations (you'll see errors otherwise)
* Calculate the LHS and RHS for all equations and show if they are equal or not

In [2]:
import numpy as np
np.random.seed(1)
A = np.random.randint(1,10, size=(4,4))
B = np.random.randint(1,10, size=(4,4))
C = np.random.randint(1,10, size=(4,4))

## Distributive Property - Matrices multiplication is distributive
### Prove that A.(B+C)=A.B+A.C

In [7]:
print(A.dot(B+C), A.dot(B)+A.dot(C),sep='\n\n')

[[219 249 229 165]
 [118 174 236 183]
 [144 181 195 146]
 [193 217 265 192]]

[[219 249 229 165]
 [118 174 236 183]
 [144 181 195 146]
 [193 217 265 192]]


## Associative Property - Matrices multiplication is associative
### Prove that A.(B.C)=(A.B).C

In [8]:
print(A.dot(B.dot(C)),(A.dot(B)).dot(C),sep='\n\n')

[[1955 2609 1627 1838]
 [1566 2136 1600 1707]
 [1496 2012 1367 1502]
 [1876 2576 1642 1846]]

[[1955 2609 1627 1838]
 [1566 2136 1600 1707]
 [1496 2012 1367 1502]
 [1876 2576 1642 1846]]


## Commutative Property - Matrix multiplication is NOT commutative
### Prove that for matrices, A.B ≠ B.A

In [9]:
print(A.dot(B),B.dot(A),sep='\n\n')

[[121 105 173  82]
 [ 58  97 150 105]
 [ 77  85 137  79]
 [ 98 116 170  88]]

[[ 79 119 117  54]
 [ 81 120 158 100]
 [ 80  85 121 114]
 [ 77 106 164 123]]


## Commutative Property -  vector multiplication IS commutative
### Prove that for vectors, x<sup>T</sup> . y = y<sup>T</sup> . x
Note: superscipt<sup>T</sup> denotes the transpose we saw earlier

In [3]:
print(A[:,0].T.dot(B[:,0]),B[:,0].T.dot(A[:,0]))
print(A[:,0],B[:,0])

78 78
[6 1 3 5] [8 7 1 4]


#### and finally 
## Simplification of the matrix product
### Prove that  (A.B)<sup>T</sup> = B<sup>T</sup> . A<sup>T</sup>

In [12]:
print((A.dot(B)).T,B.T.dot(A.T),sep='\n\n')

[[121  58  77  98]
 [105  97  85 116]
 [173 150 137 170]
 [ 82 105  79  88]]

[[121  58  77  98]
 [105  97  85 116]
 [173 150 137 170]
 [ 82 105  79  88]]


## Summary 

So now we have seen enough matrix algebra to help us solve a problem of linear equations as we saw earlier in this section. We shall see how to do this next. 